version: '2'
# Docker Compose file meant for building release packages. Use w/ docker-compose.admin.yml
services:

  phpfpm:
    volumes:
      - build_app_root:/build:rw

  # We use a node container to compile js, css, etc
  node:
    volumes:
      - build_app_root:/build:rw

volumes:
  build_app_root: {}
