version: '3.2'
services:
  app:
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/test
      - FUEL_ENV=test
      - LOG_HANDLER=DEFAULT
    volumes:
      # isolate test widget files just for test
      - static_widget_files_test:/var/www/html/public/widget
      # isolate test media just for test
      - uploaded_media_test:/var/www/html/fuel/packages/materia/media
      - ./config/php/materia.test.php.ini:/usr/local/etc/php/conf.d/test.ini

  mysql:
    environment:
      - MYSQL_DATABASE=test
    volumes:
      - "./config/mysql/dev.my.cnf:/etc/mysql/conf.d/my.cnf"
    # this makes the unit tests much faster but it's a little weird jumping
    # back and forth between running the server and testing
    # tmpfs:
    #   - /var/lib/mysql

volumes:
  static_widget_files_test: {} # contain widgets installed in tests
  uploaded_media_test: {} # contain files uploaded in tests
